# configuration
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
repository: saros-project/saros

# sass loading
sass:
    load_paths:
        - _sass
        - node_modules

# Avoid default exclude of node_modules 
include:
  - node_modules

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# custom properties

title: Saros