name: STF Tests

on:
  push:
    branches:
      - 'pr/stf/**'
      - 'master'

  workflow_dispatch:

jobs:
  stf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run STF Tests
      run: ./run_stf.sh CI

    - name: Upload STF results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: stf-test-results
        path: test_results

